### ISSUE TITLE
Request for support of 'flashlight.lib.sequence`

### ISSUE THREAD

**Issue by MorphlingEd** [flashlight/text#30]
### Feature Description
Hope the `flashlight.lib.sequence` module can be added to this repo

#### Use Case
I just moved from the original repo `flashlight` here and follow the instructions to install the python binding like below:
`cd bindings/python`
`pip install -e .`
This successfully installed the support for `flashlight.lib.text` but cannot install `flashlight.lib.sequence` which are often used with the former.

#### Additional Context
If there already exists a way to install it, please correct me. Thanks for any help in advance!

**Comment by jacobkahn** [comment]
Hi @MorphlingEd — sorry for the delay. Bindings for `flashlight.lib.sequence` now live in https://github.com/flashlight/sequence/. I'm working on making sure documentation is up to date.

Let me know if you've any problems installing.
