### ISSUE TITLE
Error in installing Python binding

### ISSUE THREAD

**Issue by mrezasoltani** [flashlight/text#31]
Hi, I am trying to install python binding for Flashlight. I first installed the following packages (I am using python 3.9.12):
pip install packaging
pip install cmake         # installed cmkae version of 3.25.0

Now if I run  the follwong command (I set (BUILD_SHARED_LIBS ON) in the begining of the CmakeList.txt file as it was complaining that the BUILD_SHARED_LIBS is off):

cmake .

I get the following error 

CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at CMakeLists.txt:8 (include):
  include could not find requested file:

    /Buildpybind11.cmake

CMake Error at CMakeLists.txt:9 (include):
  include could not find requested file:
    /pybind11Tools.cmake

CMake Error at CMakeLists.txt:21 (pybind11_add_module):
  Unknown CMake command "pybind11_add_module".
Call Stack (most recent call first):
  CMakeLists.txt:45 (add_pybind11_extension)

Can you please help me ?

**Comment by mrezasoltani** [comment]
I could resolve the errors and installed everything.

**Comment by jacobkahn** [comment]
Resolved
