### ISSUE TITLE
Online/Streaming mode

### ISSUE THREAD

**Issue by naymaraq** [flashlight/text#56]
### Question

Is there any official API/doc/example to use flashlight decoder in streaming mode?

**Comment by jacobkahn** [comment]
@naymaraq — if you're using the CTC decoder, you can pass data into `decodeStep` incrementally, and the decoder will behave in a streaming fashion. Streaming isn't currently supported for the autoregressive decoder, although that may change down the line.

There isn't documentation for streaming as it stands, but I hope to add some soon. As always, feel free to contribute back.
