### ISSUE TITLE
[A typo in Python Bindings Quickstart ]

### ISSUE THREAD

**Issue by ZL92** [flashlight/text#63]
### Bug Description
First of all, thanks for updating the Python Bindings. I think there is a typo in Quickstart. Now it is 
```
pip install git+https://github.com.kpu/kenlm.git. 
```
I think the correct one is replacing the dot after com with a forward slash, which is

```
pip install git+https://github.com/kpu/kenlm.git. 
```

#### Reproduction Steps
n/a

### Platform and Hardware
n/a

#### Additional Context
n/a

**Comment by jacobkahn** [comment]
@ZL92 — thanks for catching! Feel free to send a PR to fix; else I'll do so later today.
